version: '3.9'
services:
  node:
    image: node
    working_dir: /home/node/app
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3003:3003'
    volumes:
      - './src:/home/node/app'
  mongo:
    image: mongo
    ports:
      - '27017:27017'